// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://womywfryiogzkgpmutzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvbXl3ZnJ5aW9nemtncG11dHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTE1ODQsImV4cCI6MjA1OTc4NzU4NH0.9LiFmdAMU8ZPQhDd-0LwLPzDmdL9d-BYyXw4afaAJzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);